"""Dataset construction for the phishing URL classifier.

Two sources of data are supported:

1. `generate_synthetic_dataset()` — because this sandbox's network egress is
   restricted (no access to kaggle.com / UCI's site / huggingface.co), we
   cannot download the literal UCI/Kaggle "Phishing Websites" dataset here.
   Instead we build a large, tactic-grounded synthetic dataset:
     - Legitimate examples: a hardcoded list of 200+ real, well-known
       domains (varied categories: tech, finance, government, education,
       retail, media, etc.), wrapped in realistic-looking URLs (paths,
       query strings, subdomains like www/docs/support).
     - Phishing examples: generated by programmatically APPLYING real,
       documented phishing tactics to those same brand names and to
       randomly generated look-alike domains: typosquatting (character
       insertion/deletion/swap/homoglyph-style substitution), IP-address
       hosts, brand name stuffed into a subdomain/path on an unrelated
       domain, excessive subdomains, URL-shortener hosts, suspicious TLDs,
       hyphenated brand mimicry, https-token-in-domain tricks, etc.
   This keeps the label grounded in genuine phishing tactics rather than
   arbitrary noise.

2. `load_csv_dataset(path)` — loads a REAL external CSV (e.g. an actual
   downloaded UCI/Kaggle phishing dataset) with a `url` column (raw URLs,
   features are computed with features.extract_features) OR a CSV that
   already has one column per name in features.FEATURE_NAMES plus a
   `label` column (1 = phishing, 0 = legitimate) — the common shape UCI's
   "Phishing Websites" CSV mirrors, so it can be dropped in with
   `--csv path/to/real_dataset.csv` and used with ZERO changes to the
   feature-extraction or model code.
"""

from __future__ import annotations

import random
import string
from dataclasses import dataclass
from typing import List, Tuple

import pandas as pd

from .features import FEATURE_NAMES, SUSPICIOUS_TLDS, extract_features

# ---------------------------------------------------------------------------
# 1. Real, well-known legitimate domains (220 total), by category.
# ---------------------------------------------------------------------------

LEGITIMATE_DOMAINS = [
    # Tech / software
    "google.com", "github.com", "microsoft.com", "apple.com", "amazon.com",
    "wikipedia.org", "mozilla.org", "python.org", "stackoverflow.com",
    "linkedin.com", "reddit.com", "adobe.com", "salesforce.com", "oracle.com",
    "ibm.com", "intel.com", "nvidia.com", "cloudflare.com", "digitalocean.com",
    "atlassian.com", "slack.com", "zoom.us", "dropbox.com", "notion.so",
    "figma.com", "canva.com", "spotify.com", "netflix.com", "twitch.tv",
    "discord.com", "wordpress.com", "shopify.com", "wikimedia.org",
    "mongodb.com", "docker.com", "kubernetes.io", "npmjs.com", "pypi.org",
    "readthedocs.io", "gitlab.com", "bitbucket.org", "jetbrains.com",
    "unity.com", "epicgames.com", "steamcommunity.com", "steampowered.com",
    "asus.com", "dell.com", "hp.com", "lenovo.com", "samsung.com", "sony.com",
    "lg.com", "qualcomm.com", "amd.com", "cisco.com", "vmware.com",
    "redhat.com", "canonical.com", "debian.org", "ubuntu.com", "apache.org",
    # Finance / banking
    "chase.com", "bankofamerica.com", "wellsfargo.com", "citibank.com",
    "hsbc.com", "americanexpress.com", "capitalone.com", "usbank.com",
    "pnc.com", "tdbank.com", "schwab.com", "fidelity.com", "vanguard.com",
    "paypal.com", "stripe.com", "square.com", "coinbase.com", "visa.com",
    "mastercard.com", "discover.com", "barclays.co.uk", "hdfcbank.com",
    "icicibank.com", "sbi.co.in", "axisbank.com", "kotak.com",
    # E-commerce / retail
    "walmart.com", "target.com", "costco.com", "bestbuy.com", "ebay.com",
    "etsy.com", "alibaba.com", "aliexpress.com", "ikea.com", "homedepot.com",
    "nike.com", "adidas.com", "zara.com", "hm.com", "flipkart.com",
    "myntra.com", "nykaa.com", "ajio.com", "swiggy.com", "zomato.com",
    # Media / news
    "nytimes.com", "bbc.com", "cnn.com", "reuters.com", "bloomberg.com",
    "theguardian.com", "forbes.com", "wsj.com", "economist.com", "npr.org",
    "aljazeera.com", "washingtonpost.com", "timesofindia.com", "ndtv.com",
    "hindustantimes.com", "thehindu.com", "indianexpress.com",
    # Education / government / nonprofit
    "harvard.edu", "mit.edu", "stanford.edu", "berkeley.edu", "ucsd.edu",
    "ox.ac.uk", "cam.ac.uk", "iitb.ac.in", "iitd.ac.in", "iisc.ac.in",
    "usa.gov", "irs.gov", "cdc.gov", "nasa.gov", "who.int", "un.org",
    "gov.uk", "india.gov.in", "unicef.org", "redcross.org", "wwf.org",
    "edx.org", "coursera.org", "khanacademy.org", "udemy.com", "ted.com",
    # Travel / airlines
    "airbnb.com", "booking.com", "expedia.com", "tripadvisor.com",
    "delta.com", "united.com", "aa.com", "emirates.com", "ryanair.com",
    "lufthansa.com", "airindia.in", "indigo.in", "makemytrip.com",
    "uber.com", "lyft.com", "ola.cabin",
    # Social / communication
    "facebook.com", "instagram.com", "twitter.com", "x.com", "pinterest.com",
    "snapchat.com", "tumblr.com", "whatsapp.com", "telegram.org", "skype.com",
    "gmail.com", "outlook.com", "yahoo.com", "protonmail.com", "icloud.com",
    # Misc well-known
    "wikihow.com", "imdb.com", "yelp.com", "craigslist.org", "quora.com",
    "medium.com", "substack.com", "patreon.com", "kickstarter.com",
    "indiegogo.com", "change.org", "archive.org", "duckduckgo.com",
    "bing.com", "yahoo.co.jp", "baidu.com", "yandex.com", "tencent.com",
    "sap.com", "workday.com", "servicenow.com", "hubspot.com", "zendesk.com",
    "mailchimp.com", "twilio.com", "okta.com", "auth0.com", "datadoghq.com",
    "newrelic.com", "sentry.io", "heroku.com", "vercel.com", "netlify.com",
    "airtable.com", "asana.com", "trello.com", "monday.com", "clickup.com",
    "evernote.com", "grammarly.com", "canva.com", "behance.net", "dribbble.com",
    "vimeo.com", "soundcloud.com", "bandcamp.com", "audible.com",
    "goodreads.com", "wattpad.com", "duolingo.com", "chess.com",
    "weather.com", "accuweather.com", "espn.com", "nba.com", "fifa.com",
    "olympics.com", "nationalgeographic.com", "history.com", "britannica.com",
    "webmd.com", "mayoclinic.org", "nih.gov", "fda.gov",
]

PATH_TEMPLATES = [
    "", "/", "/login", "/account", "/products", "/about", "/contact",
    "/support", "/help", "/en/home", "/blog/2026/update", "/search?q=news",
    "/docs/api", "/careers", "/pricing", "/dashboard", "/settings/profile",
    "/store/checkout", "/news/latest", "/downloads",
]

SUBDOMAIN_TEMPLATES = ["", "www.", "www.", "www.", "docs.", "support.", "m.", "app.", "shop.", "mail."]

BRAND_KEYWORDS = list({
    "paypal", "apple", "microsoft", "amazon", "google", "facebook",
    "netflix", "bankofamerica", "wellsfargo", "chase", "citibank", "hsbc",
    "instagram", "linkedin", "dropbox", "adobe", "ebay", "walmart",
    "americanexpress", "irs", "coinbase", "binance", "outlook", "office365",
})

RANDOM_WORDS = [
    "secure", "verify", "update", "account", "login", "confirm", "billing",
    "support", "service", "alert", "signin", "portal", "session", "id",
    "auth", "recover", "unlock", "validate", "center", "team", "info",
]

TYPO_TLDS = ["com", "net", "info", "biz", "co", "cc"]


def _rand_str(n: int, alphabet: str = string.ascii_lowercase) -> str:
    return "".join(random.choice(alphabet) for _ in range(n))


def _homoglyph_swap(brand: str) -> str:
    """Swap one character for a visually similar one (classic homograph
    typosquatting tactic, e.g. o->0, l->1, e->3)."""
    swaps = {"o": "0", "l": "1", "i": "1", "e": "3", "a": "4", "s": "5"}
    chars = list(brand)
    candidates = [i for i, c in enumerate(chars) if c in swaps]
    if not candidates:
        return brand
    i = random.choice(candidates)
    chars[i] = swaps[chars[i]]
    return "".join(chars)


def _typo_variants(brand: str) -> str:
    """Apply one random typosquatting edit: insertion, deletion, swap,
    duplication, or homoglyph substitution."""
    op = random.choice(["insert", "delete", "swap", "duplicate", "homoglyph", "hyphen"])
    chars = list(brand)
    if op == "insert" and chars:
        i = random.randint(0, len(chars))
        chars.insert(i, random.choice(string.ascii_lowercase))
    elif op == "delete" and len(chars) > 3:
        i = random.randint(0, len(chars) - 1)
        del chars[i]
    elif op == "swap" and len(chars) > 1:
        i = random.randint(0, len(chars) - 2)
        chars[i], chars[i + 1] = chars[i + 1], chars[i]
    elif op == "duplicate" and chars:
        i = random.randint(0, len(chars) - 1)
        chars.insert(i, chars[i])
    elif op == "homoglyph":
        return _homoglyph_swap(brand)
    elif op == "hyphen" and len(chars) > 2:
        i = random.randint(1, len(chars) - 1)
        chars.insert(i, "-")
    return "".join(chars)


@dataclass
class UrlRecord:
    url: str
    label: int  # 1 = phishing, 0 = legitimate


def _make_legitimate_url(domain: str) -> str:
    sub = random.choice(SUBDOMAIN_TEMPLATES)
    path = random.choice(PATH_TEMPLATES)
    scheme = "https"  # real major sites overwhelmingly serve HTTPS today
    return f"{scheme}://{sub}{domain}{path}"


def _make_phishing_url() -> str:
    """Generate one phishing-style URL using a randomly chosen real tactic."""
    tactic = random.choice([
        "typosquat", "typosquat", "ip_host", "brand_in_subdomain",
        "brand_in_path", "excess_subdomains", "shortener",
        "suspicious_tld", "https_token", "long_random_host",
    ])
    scheme = random.choice(["http", "http", "https"])

    if tactic == "typosquat":
        brand = random.choice(BRAND_KEYWORDS)
        fake = _typo_variants(brand)
        tld = random.choice(TYPO_TLDS)
        path = random.choice(["/login", "/signin", "/verify", "/account/update", ""])
        return f"{scheme}://{fake}.{tld}{path}"

    if tactic == "ip_host":
        ip = ".".join(str(random.randint(1, 254)) for _ in range(4))
        path = random.choice(["/login.php", "/secure/verify", "/account", "/webscr"])
        return f"{scheme}://{ip}{path}"

    if tactic == "brand_in_subdomain":
        brand = random.choice(BRAND_KEYWORDS)
        word = random.choice(RANDOM_WORDS)
        filler = _rand_str(random.randint(4, 8))
        return f"{scheme}://{brand}.{word}-{filler}.com/login"

    if tactic == "brand_in_path":
        brand = random.choice(BRAND_KEYWORDS)
        filler = _rand_str(random.randint(5, 9))
        tld = random.choice(TYPO_TLDS)
        return f"{scheme}://{filler}-portal.{tld}/{brand}/secure/login"

    if tactic == "excess_subdomains":
        brand = random.choice(BRAND_KEYWORDS)
        chain = ".".join(random.choice(RANDOM_WORDS) for _ in range(random.randint(3, 5)))
        filler = _rand_str(6)
        return f"{scheme}://{brand}.{chain}.{filler}.com/"

    if tactic == "shortener":
        from .features import URL_SHORTENERS
        host = random.choice(sorted(URL_SHORTENERS))
        code = _rand_str(7, string.ascii_letters + string.digits)
        return f"{scheme}://{host}/{code}"

    if tactic == "suspicious_tld":
        brand = random.choice(BRAND_KEYWORDS + [""])
        filler = _rand_str(random.randint(6, 10))
        tld = random.choice(sorted(SUSPICIOUS_TLDS))
        host = f"{brand}-{filler}" if brand else filler
        return f"{scheme}://{host}.{tld}/verify"

    if tactic == "https_token":
        brand = random.choice(BRAND_KEYWORDS)
        filler = _rand_str(5)
        return f"http://https-{brand}-{filler}-secure.com/login"

    # long_random_host
    filler = _rand_str(random.randint(18, 30))
    word = random.choice(RANDOM_WORDS)
    return f"{scheme}://{word}-{filler}.net/account/{_rand_str(6)}"


def generate_synthetic_dataset(n_per_class: int = 800, seed: int = 42) -> pd.DataFrame:
    """Build a balanced, tactic-grounded synthetic dataset.

    Legitimate examples are drawn (with repetition + varied paths/subdomains)
    from `LEGITIMATE_DOMAINS`. Phishing examples are generated by applying
    genuine, documented phishing tactics (see `_make_phishing_url`).

    Returns a DataFrame with one `url` column and one `label` column
    (1 = phishing, 0 = legitimate).
    """
    rng = random.Random(seed)
    random.seed(seed)  # module-level helpers above use the global RNG

    legit_records: List[UrlRecord] = []
    seen = set()
    attempts = 0
    while len(legit_records) < n_per_class and attempts < n_per_class * 20:
        attempts += 1
        domain = rng.choice(LEGITIMATE_DOMAINS)
        url = _make_legitimate_url(domain)
        if url in seen:
            continue
        seen.add(url)
        legit_records.append(UrlRecord(url=url, label=0))

    phish_records: List[UrlRecord] = []
    attempts = 0
    while len(phish_records) < n_per_class and attempts < n_per_class * 20:
        attempts += 1
        url = _make_phishing_url()
        if url in seen:
            continue
        seen.add(url)
        phish_records.append(UrlRecord(url=url, label=1))

    all_records = legit_records + phish_records
    rng.shuffle(all_records)
    df = pd.DataFrame([{"url": r.url, "label": r.label} for r in all_records])
    return df


def featurize_dataframe(df: pd.DataFrame) -> pd.DataFrame:
    """Given a DataFrame with a `url` and `label` column, compute the full
    lexical feature matrix and return a DataFrame with FEATURE_NAMES columns
    plus `label` (and `url` retained for reference)."""
    rows = []
    for _, row in df.iterrows():
        feats = extract_features(row["url"])
        feats["label"] = row["label"]
        feats["url"] = row["url"]
        rows.append(feats)
    out = pd.DataFrame(rows)
    return out[FEATURE_NAMES + ["label", "url"]]


def load_csv_dataset(path: str) -> pd.DataFrame:
    """Load an external (real UCI/Kaggle-style) CSV dataset.

    Supports two shapes:
      (a) a `url` column (+ optional `label`) — features are computed here
          with the same extract_features() used everywhere else.
      (b) a CSV that already has one column per FEATURE_NAMES entry plus a
          `label`/`Result`/`class` column — used as-is (only the label
          column is normalized to `label` with 1=phishing, 0=legitimate).

    Returns a DataFrame with FEATURE_NAMES + label (+ url when available),
    matching the shape `featurize_dataframe` produces, so the rest of the
    pipeline (model.py) needs no changes to consume real data.
    """
    raw = pd.read_csv(path)
    cols_lower = {c.lower(): c for c in raw.columns}

    if "url" in cols_lower:
        url_col = cols_lower["url"]
        label_col = None
        for cand in ("label", "class", "result", "y"):
            if cand in cols_lower:
                label_col = cols_lower[cand]
                break
        df = pd.DataFrame({"url": raw[url_col]})
        if label_col is not None:
            df["label"] = _normalize_labels(raw[label_col])
        else:
            raise ValueError(
                "CSV has a 'url' column but no recognizable label column "
                "(expected one of: label, class, result, y)."
            )
        return featurize_dataframe(df)

    # Shape (b): already-featurized CSV (e.g. UCI 'Phishing Websites' style)
    missing = [f for f in FEATURE_NAMES if f not in raw.columns]
    if missing:
        raise ValueError(
            "CSV does not have a 'url' column, and is missing expected "
            f"feature columns to be used as a pre-featurized dataset: {missing}. "
            "Provide either a raw 'url' (+ label) column, or a CSV whose "
            f"columns match phishing_detector.features.FEATURE_NAMES: {FEATURE_NAMES}"
        )
    label_col = None
    for cand in ("label", "class", "result", "y"):
        if cand in cols_lower:
            label_col = cols_lower[cand]
            break
    if label_col is None:
        raise ValueError("Featurized CSV is missing a label column (label/class/result/y).")

    out = raw[FEATURE_NAMES].copy()
    out["label"] = _normalize_labels(raw[label_col])
    if "url" in raw.columns:
        out["url"] = raw["url"]
    else:
        out["url"] = ""
    return out


def _normalize_labels(series: pd.Series) -> pd.Series:
    """Normalize a label column to 1=phishing / 0=legitimate.

    Handles common encodings seen in real datasets: {1,0}, {1,-1} (UCI uses
    -1 for legitimate, 1 for phishing), {'phishing','legitimate'}, {'bad','good'}.
    """
    if series.dtype == object:
        mapped = series.str.strip().str.lower().map({
            "phishing": 1, "phish": 1, "bad": 1, "malicious": 1, "1": 1,
            "legitimate": 0, "legit": 0, "good": 0, "benign": 0, "0": 0, "-1": 0,
        })
        if mapped.isna().any():
            raise ValueError(f"Could not normalize label values: {series.unique()}")
        return mapped.astype(int)
    numeric = series.astype(int)
    if set(numeric.unique()) <= {1, -1}:
        return numeric.map({1: 1, -1: 0})
    return numeric
